import { parseInsights } from "../utils/parseInsights";

function Section({ title, points, tone }) {
  return (
    <div className={`rounded-xl p-4 text-slate-900 dark:text-slate-100 ${tone}`}>
      <h3 className="font-semibold">{title}</h3>
      <ol className="mt-2 list-decimal space-y-1 pl-5 text-sm">
        {(points?.length ? points : ["No data", "No data", "No data"]).map((item, idx) => (
          <li key={`${title}-${idx}`}>{item}</li>
        ))}
      </ol>
    </div>
  );
}

export default function AIInsightsCard({ insightsText, errorMessage, isHeuristic = false }) {
  const sections = parseInsights(insightsText);
  const hasInsights =
    sections.strengths.length ||
    sections.weaknesses.length ||
    sections.improvements.length;

  return (
    <div className="glass-card p-6 fade-up">
      <div className="flex items-center justify-between">
        <h2 className="text-xl font-semibold">AI Insights</h2>
        {isHeuristic ? (
          <span className="ml-3 rounded-md bg-slate-100 px-2 py-1 text-xs text-slate-700">
            Generated by heuristics
          </span>
        ) : null}
      </div>
      {errorMessage && !hasInsights ? (
        <p className="mt-3 rounded-lg bg-rose-50 px-3 py-2 text-sm text-rose-700">
          {errorMessage}
        </p>
      ) : !hasInsights ? (
        <p className="mt-3 rounded-lg bg-yellow-50 px-3 py-2 text-sm text-yellow-800">
          No AI insights available. Please ensure the backend is running or try again.
        </p>
      ) : (
        <div className="mt-4 grid gap-3 md:grid-cols-3">
          <Section
            title="Strengths"
            points={sections.strengths}
            tone="bg-emerald-50 dark:bg-emerald-900/35"
          />
          <Section
            title="Weaknesses"
            points={sections.weaknesses}
            tone="bg-rose-50 dark:bg-rose-900/35"
          />
          <Section
            title="Improvements"
            points={sections.improvements}
            tone="bg-amber-50 dark:bg-amber-900/35"
          />
        </div>
      )}
    </div>
  );
}
